project_id = "oimhwdymghkwxznjarkv"

[functions.game-wipe]
verify_jwt = true

[functions.shop-purchase]
verify_jwt = true

[functions.sync-mintbase-nfts]
verify_jwt = true

[functions.check-nft-whitelist]
verify_jwt = false

[functions.get-user-nft-cards]
verify_jwt = false

[functions.marketplace-buy-nft]
verify_jwt = false

[functions.marketplace-create-nft-listing]
verify_jwt = false
