project_id = "oimhwdymghkwxznjarkv"

[functions.sync-nft-cards]
verify_jwt = true

[functions.game-wipe]
verify_jwt = true

[functions.shop-purchase]
verify_jwt = true

[functions.sync-mintbase-nfts]
verify_jwt = true

[functions.check-nft-whitelist]
verify_jwt = false

[functions.validate-nft-whitelist]
verify_jwt = false

[functions.get-user-nft-cards]
verify_jwt = true

[functions.marketplace-buy-nft]
verify_jwt = true

[functions.marketplace-create-nft-listing]
verify_jwt = true

[functions.open-card-packs]
verify_jwt = true

[functions.upload-item-image]
verify_jwt = false

[functions.sync-all-inventories]
verify_jwt = true

[functions.upload-building-background]
verify_jwt = false

[functions.upload-monster-image]
verify_jwt = false
